#!/bin/sh
case $# in
0) echo " " ; echo "  " ; echo " g++ compilation of a file using c++11 standard and using SIMD Vc for vectorization"
echo '			usage: "doCompile <filename w/o extn.>" '; echo "  " ;exit 0;;
*) echo " ";;
esac
rm -rf $1.ee
g++ -I $VCROOT/include -L $VCROOT/lib -std=c++11 -g $1.cpp -o $1.ee -lVc

